PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = XDesktopWindow 

-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble
