
include $(GNUSTEP_MAKEFILES)/common.make

include ../gworkspace.make

SUBPROJECTS = BrowserViewer \
	      IconsViewer \
	      SmallIconsViewer 
	      
-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

