# Additional flags to pass to the preprocessor
ADDITIONAL_CPPFLAGS += 

# Additional flags to pass to the Objective-C compiler
ADDITIONAL_OBJCFLAGS += -Wall

# Additional flags to pass to the C compiler
ADDITIONAL_CFLAGS += -Wall

# Additional include directories the compiler should search
#ADDITIONAL_INCLUDE_DIRS += 

# Additional LDFLAGS to pass to the linker
ADDITIONAL_LDFLAGS += 

ADDITIONAL_TOOL_LIBS +=

thumbnailer_TOOL_LIBS += $(GUI_LIBS) $(SYSTEM_LIBS)
