
PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make


#
# subprojects
#
SUBPROJECTS = ImageThumbnailer

-include GNUmakefile.preamble
-include GNUmakefile.local

-include $(GNUSTEP_MAKEFILES)/tool.make
-include $(GNUSTEP_MAKEFILES)/service.make
-include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.local.service
-include GNUmakefile.postamble

