# Additional flags to pass to the preprocessor
ADDITIONAL_CPPFLAGS += 

# Additional flags to pass to the Objective-C compiler
ADDITIONAL_OBJCFLAGS += -Wall

# Additional flags to pass to the C compiler
ADDITIONAL_CFLAGS += -Wall

# Additional include directories the compiler should search
ADDITIONAL_INCLUDE_DIRS += -I../

# Additional LDFLAGS to pass to the linker
ADDITIONAL_LDFLAGS += 

ADDITIONAL_TOOL_LIBS +=

LIBRARIES_DEPEND_UPON += $(GUI_LIBS) $(FND_LIBS) $(OBJC_LIBS) $(SYSTEM_LIBS)
