#!/bin/sh

if [ "$1" = "-GSFilePath" ] || [ "$1" = "-GSTempPath" ]; then
   file="$2"
else
   file="$1"
fi

if [ test -z "$file" ]; then 
   xmms &
   exit
fi

ACTION=`defaults read XMMS FileOpenAction`


if [ "$ACTION" = "XMMS FileOpenAction 'EnqueueAndPlay'" ]; then

   if [ ! "test -z '`which xmms-add-play`'" ]; then
	echo "Cannot find xmms-add-play - will enqueue instead."
	xmms -e "$file" &
   else if ! [ test -z "`echo '$file' |  grep '.pls' || '.m3u'`" ]; then
           xmms-add-play "$file" &
	   # xmms -e -p "$file" &
	else
	    # xmms-add-play does not support playlists
	    xmms -e "$file"  & 
        fi
        # xmms -p & # if xmms is currently not playing we need to make it play 
   fi
else if [ "$ACTION"  = "XMMS FileOpenAction 'Enqueue'" ]; then
        xmms -e "$file" &
     else
	xmms "$file" & 
     fi 
fi

