#!/bin/sh

if [ "$1" = "-GSFilePath" ] || [ "$1" = "-GSTempPath" ]; then
   file=$2
else
   file=$1
fi

ACTION=`defaults read XMMS FileOpenAction`


if [ "$ACTION"  = "XMMS FileOpenAction 'Enqueue'" ]; then
   xmms -e "$file" &
else
   xmms "$file" & 
fi

