include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
        fswatcher \
        searchtool \
        ddbd \
        thumbnailer \
        wopen 

-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

