include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
  TextExtractor \
  JpegExtractor 
  
-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

